swagger: "2.0"
info:
  title: andytest
  description: "Get the name of an airport from its three-letter IATA code."
  version: "1.0.0"
schemes:
  - "https"
x-google-backend:
  address: https://hello-586737312065.europe-west2.run.app
produces:
- application/json
paths:
  "/hello":
    get:
      description: "Say hello"
      operationId: "hello"
      parameters:
        -
          name: name
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The name is invalid or missing."
